// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onmdwxhsllqxzwkkubwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ubWR3eGhzbGxxeHp3a2t1YndqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNzMyNzUsImV4cCI6MjA1ODY0OTI3NX0.eW6LQUHx-d7eMdqz_WEpiF_xEENURml2oU2_FAJCe7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);